import swaggerAutogen from 'swagger-autogen';

const doc = {
  info: {
    title: 'EdgeReach CRM API',
    description: 'API documentation for EdgeReach CRM',
    version: '1.0.0',
  },
  host: 'localhost:3001',
  basePath: '/api',
  schemes: ['http', 'https'],
  securityDefinitions: {
    bearerAuth: {
      type: 'apiKey',
      name: 'Authorization',
      in: 'header',
    },
  },
  definitions: {
    Lead: {
      id: 'uuid',
      tenant_id: 'uuid',
      first_name: 'string',
      last_name: 'string',
      email: 'string',
      company: 'string',
      phone: 'string',
      source: { type: 'string', enum: ['website', 'linkedin', 'referral', 'other'] },
      status: { type: 'string', enum: ['new', 'contacted', 'qualified', 'unqualified'] },
      score: { type: 'number', minimum: 0, maximum: 100 },
      owner_id: 'uuid',
      notes: 'string',
      last_contacted: 'date',
      created_at: 'date',
      updated_at: 'date',
    },
    Opportunity: {
      id: 'uuid',
      tenant_id: 'uuid',
      name: 'string',
      value: 'number',
      stage: { type: 'string', enum: ['qualified', 'discovery', 'proposal', 'negotiation', 'closed_won', 'closed_lost'] },
      probability: { type: 'number', minimum: 0, maximum: 100 },
      expected_close_date: 'date',
      lead_id: 'uuid',
      owner_id: 'uuid',
      notes: 'string',
      last_activity_date: 'date',
      created_at: 'date',
      updated_at: 'date',
    },
    Contact: {
      id: 'uuid',
      tenant_id: 'uuid',
      firstName: 'string',
      lastName: 'string',
      email: 'string',
      phone: 'string',
      role: { type: 'string', enum: ['decision_maker', 'influencer', 'evaluator', 'gatekeeper', 'other'] },
      title: 'string',
      account_id: 'uuid',
      opt_out: 'boolean',
      last_activity_date: 'date',
      preferences: {
        email_marketing: 'boolean',
        newsletter: 'boolean',
        communication_frequency: { type: 'string', enum: ['daily', 'weekly', 'monthly', 'none'] },
      },
      created_at: 'date',
      updated_at: 'date',
    },
    Account: {
      id: 'uuid',
      tenant_id: 'uuid',
      name: 'string',
      industry: 'string',
      website: 'string',
      size: { type: 'string', enum: ['small', 'medium', 'large', 'enterprise'] },
      parent_account_id: 'uuid',
      annual_revenue: 'number',
      owner_id: 'uuid',
      created_at: 'date',
      updated_at: 'date',
    },
    Campaign: {
      id: 'uuid',
      tenant_id: 'uuid',
      name: 'string',
      type: { type: 'string', enum: ['email', 'newsletter', 'nurture', 'webinar', 'social', 'event'] },
      status: { type: 'string', enum: ['draft', 'scheduled', 'active', 'paused', 'completed', 'cancelled'] },
      owner_id: 'uuid',
      description: 'string',
      start_date: 'date',
      end_date: 'date',
      budget: 'number',
      segment: {
        filters: [{
          field: 'string',
          operator: { type: 'string', enum: ['equals', 'not_equals', 'contains', 'not_contains', 'greater_than', 'less_than'] },
          value: 'object',
        }],
      },
      template: {
        subject: 'string',
        content: 'string',
        variables: ['string'],
      },
      metrics: {
        sent: 'number',
        opened: 'number',
        clicked: 'number',
        converted: 'number',
        revenue: 'number',
      },
      created_at: 'date',
      updated_at: 'date',
    },
    User: {
      id: 'uuid',
      tenant_id: 'uuid',
      email: 'string',
      first_name: 'string',
      last_name: 'string',
      role: { type: 'string', enum: ['manager', 'sales_rep'] },
      status: { type: 'string', enum: ['active', 'inactive', 'pending'] },
      avatar_url: 'string',
      preferences: {
        default_dashboard: 'string',
        notification_settings: {
          email: 'boolean',
          push: 'boolean',
          digest_frequency: { type: 'string', enum: ['never', 'daily', 'weekly'] },
        },
        theme: { type: 'string', enum: ['light', 'dark', 'system'] },
      },
      quota: {
        leads: 'number',
        revenue: 'number',
        period: { type: 'string', enum: ['monthly', 'quarterly', 'yearly'] },
      },
      created_at: 'date',
      updated_at: 'date',
    },
    Task: {
      id: 'uuid',
      tenant_id: 'uuid',
      title: 'string',
      description: 'string',
      due_date: 'date',
      priority: { type: 'string', enum: ['low', 'medium', 'high', 'urgent'] },
      status: { type: 'string', enum: ['pending', 'in_progress', 'completed', 'cancelled'] },
      type: { type: 'string', enum: ['call', 'email', 'meeting', 'follow_up', 'other'] },
      entity_type: { type: 'string', enum: ['lead', 'opportunity', 'contact', 'account'] },
      entity_id: 'uuid',
      assignee_id: 'uuid',
      workflow_id: 'uuid',
      completed_at: 'date',
      created_at: 'date',
      updated_at: 'date',
    },
    Report: {
      id: 'uuid',
      tenant_id: 'uuid',
      name: 'string',
      description: 'string',
      type: { type: 'string', enum: ['sales', 'leads', 'activities', 'performance', 'custom'] },
      query: {
        metrics: ['string'],
        dimensions: ['string'],
        filters: [{
          field: 'string',
          operator: { type: 'string', enum: ['equals', 'not_equals', 'greater_than', 'less_than', 'contains', 'not_contains'] },
          value: 'object',
        }],
        sort: [{
          field: 'string',
          direction: { type: 'string', enum: ['asc', 'desc'] },
        }],
        limit: 'number',
      },
      created_at: 'date',
      updated_at: 'date',
    },
    Integration: {
      id: 'uuid',
      tenant_id: 'uuid',
      provider: { type: 'string', enum: ['linkedin', 'gmail', 'google_calendar'] },
      name: 'string',
      config: {
        credentials: {
          access_token: 'string',
          refresh_token: 'string',
          expires_at: 'date',
        },
        settings: 'object',
      },
      status: { type: 'string', enum: ['active', 'inactive', 'error'] },
      last_sync: 'date',
      error: 'string',
      created_at: 'date',
      updated_at: 'date',
    },
    Dashboard: {
      id: 'uuid',
      tenant_id: 'uuid',
      name: 'string',
      description: 'string',
      layout: [{
        id: 'string',
        type: { type: 'string', enum: ['chart', 'metric', 'table', 'list'] },
        config: {
          data_source: 'string',
          metrics: ['string'],
          filters: [{
            field: 'string',
            operator: 'string',
            value: 'object',
          }],
          refresh_interval: 'number',
        },
      }],
      is_default: 'boolean',
      owner_id: 'uuid',
      created_at: 'date',
      updated_at: 'date',
    },
  },
};

const outputFile = './src/swagger-output.json';
const routes = [
  './src/routes/accounts.ts',
  './src/routes/auth.ts',
  './src/routes/campaigns.ts',
  './src/routes/contacts.ts',
  './src/routes/dashboard.routes.ts',
  './src/routes/integration.routes.ts',
  './src/routes/leads.ts',
  './src/routes/opportunities.ts',
  './src/routes/report.routes.ts',
  './src/routes/users.ts',
  './src/index.ts',
];

swaggerAutogen()(outputFile, routes, doc);